name: link_saver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  links_api:
    path: packages/links_api
  links_repository:
    path: packages/links_repository

  sqflite_links:
    path: packages/sqflite_links

  google_fonts: ^3.0.1
  google_sign_in: ^5.4.4
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  flutter_phoenix: ^1.1.0
  url_launcher: ^6.1.8
  in_app_review: ^2.0.6
  google_mobile_ads: ^2.3.0
  shared_preferences: ^2.0.17
  fluttertoast: ^8.1.2
  share_plus: ^6.3.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/hyperlink.png
    - assets/folder.png

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/hyperlink.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"