name: sqflite_links
description: A Flutter implementation of the Links that uses sqlite.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  path_provider: ^2.0.11
  links_api:
    path: ../links_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
